gclouddatastore:
  image: risaacson/gcd-local:v1beta2-rev1-3.0.0
  environment:
    - PROJ_ID=suppliers
    - CONSISTENCY=1.0
  ports:
    - '8080'

postcodesapi:
  image: eu.gcr.io/first-footing-108508/postcodes-api:dev
  environment:
    - DATASTORE_HOST=http://gclouddatastore:8080
    - GCLOUD_PROJECT_ID=suppliers
    - GCLOUD_KEY=ewogICJwcml2YXRlX2tleV9pZCI6ICIxMjM0NSIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuMTIzNDU2Nzg5XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiMTIzLmRldmVsb3Blci5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEyMy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsCiAgInR5cGUiOiAic2VydmljZV9hY2NvdW50Igp9Cg==
  ports:
    - '8080'
  links:
    - gclouddatastore

api:
  build: .
  ports:
    - '8080'
  links:
    - gclouddatastore
    - postcodesapi
  environment:
    - POSTCODES_API_SVC_HOST=postcodesapi
    - POSTCODES_API_SVC_PORT=8080
    - DATASTORE_HOST=http://gclouddatastore:8080
    - GCLOUD_PROJECT_ID=suppliers
    - GCLOUD_KEY=ewogICJwcml2YXRlX2tleV9pZCI6ICIxMjM0NSIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuMTIzNDU2Nzg5XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiMTIzLmRldmVsb3Blci5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEyMy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsCiAgInR5cGUiOiAic2VydmljZV9hY2NvdW50Igp9Cg==

dev:
  build: .
  ports:
    - '8080'
  volumes:
    - .:/src
  links:
    - gclouddatastore
    - postcodesapi
  environment:
    - POSTCODES_API_SVC_HOST=postcodesapi
    - POSTCODES_API_SVC_PORT=8080
    - DATASTORE_HOST=http://gclouddatastore:8080
    - GCLOUD_PROJECT_ID=suppliers
    - GCLOUD_KEY=ewogICJwcml2YXRlX2tleV9pZCI6ICIxMjM0NSIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuMTIzNDU2Nzg5XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiMTIzLmRldmVsb3Blci5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEyMy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsCiAgInR5cGUiOiAic2VydmljZV9hY2NvdW50Igp9Cg==
  command: bash -c "npm install && npm run watch"
